### ISSUE TITLE
What's point of this library?

### ISSUE THREAD

**Issue by holyxiaoxin** [appcues/exconstructor#2]
I'm not sure if I'm missing anything but I can't see the point of this library.

Native: `struct = struct(TestStruct, map)`
Exconstructor: `struct = TestStruct.new(map)`

**Comment by gamache** [comment]
Let's consider TestStruct as follows:

``` elixir
defmodule TestStruct do
  defstruct some_field: nil
end
```

The native solution you presented works when `map` is a map or a keyword list, with atoms as keys:

``` elixir
struct(TestStruct, %{some_field: 1})  # => %TestStruct{some_field: 1}
struct(TestStruct, [some_field: 1])   # => %TestStruct{some_field: 1}
```

But it does not work when the keys are strings:

``` elixir
struct(TestStruct, %{"some_field" => 1})  # => %TestStruct{some_field: nil}
struct(TestStruct, [{"some_field", 1}])   # => %TestStruct{some_field: nil}
```

And it certainly doesn't work when the input map contains camelCase versions of under_scored struct fields (or vice versa):

``` elixir
struct(TestStruct, %{someField: 1})  # => %TestStruct{some_field: nil}
```

ExConstructor handles all these kinds of input -- map or keyword list (like the native version), and also atom or string keys (unlike native) and camelCase/under_scored field names (unlike native).

**Comment by holyxiaoxin** [comment]
Ahh. I just saw this. Thanks mate. (:

```
The generated constructor, called new by default, 
handles map-vs-keyword-list, string-vs-atom, 
and camelCase-vs-under_score input data issues automatically, 
DRYing up your code and letting you move on to the interesting parts of your program.
```
