### ISSUE TITLE
Is this safe to use with user input?

### ISSUE THREAD

**Issue by aaronjensen** [appcues/exconstructor#5]
Unless I'm missing something, it looks like this calls `String.to_atom/1` on maps that could come from url params, which, given that atoms are never garbage collected exposes a denial of service vulnerability. Maybe I'm missing some validation somewhere, but it seems like this would need to verify that each key string is actually a key and never turn user input into atoms.

See: https://github.com/appcues/exconstructor/blob/master/lib/exconstructor.ex#L155-L156

**Comment by gamache** [comment]
ExConstructor is safe to use on untrusted input.  In the lines you reference, the string `str` originates from `atom`, which comes through an `Enum.reduce` statement from `keys`, which in turn comes from the `struct` supplied by the programmer, not the `map_or_kwlist` coming from the outside world.

I should note this more clearly in the project documentation.  Thanks for writing!

**Comment by aaronjensen** [comment]
Great, thanks for the clarification!
