### ISSUE TITLE
Support for nested structs

### ISSUE THREAD

**Issue by anronin** [appcues/exconstructor#8]
It will be nice if you can pass a few structs and get something like:
from
`%{"Command" => "string",
  "Created" => 1459328030, "HostConfig" => %{"NetworkMode" => "default"}}`
to
`%Container{command: "string",
 created: 1459328030, %HostConfig{network_mode: "default"}}`

if it possible. Maybe from nested module:

```
defmodule Constructor do

  defmodule Container do
    defstruct command: 1, created: 2, host_config: 3

    use ExConstructor
  end

  defmodule HostConfig do
    defstruct network_mode: 1 #(or 4)

    use ExConstructor
  end
end
```

**Comment by jschoch** [comment]
Looks like nested structs are working here: SLOBYYYY/exconstructor

Can this be merged in?

**Comment by gamache** [comment]
@jschoch Sorry for the delayed reply.  The PR you reference doesn't make nested structs work in a configurable way.  I like the syntax proposal in #18, so I am going to use that as the active ticket for this going forward. :+1:
